<?php namespace yuanhuanonline\myplayer;
 use Flarum\Extend;
 use s9e\TextFormatter\Configurator;
 use Flarum\Frontend\Document;
 return [(new Extend\Frontend("forum"))->content(function (Document $document) { $document->head[] = '       <link rel="stylesheet" href="https://cdn.g-7.net/APlayer.min.css">\15\xa       <script src="https://cdn.g-7.net/APlayer.min.js"></script>\xd\12       <script src="https://cdn.g-7.net/Meting.js"></script>';
 }), (new Extend\Formatter())->configure(function (Configurator $config) { goto OyxOU5pKli;
 D3FhhE0mwa: $config->MediaEmbed->add("niconico", ["host" => ["nicovideo.jp", "nico.ms"], "extract" => ["!nicovideo\.jp/watch/sm(?'smid'[-0-9]+)!", "!nico\.ms/sm(?'smid'[-0-9]+)!"], "iframe" => ["src" => "//embed.nicovideo.jp/watch/sm{@smid}"]]);
 goto khjBuvQfbF;
 Dn6LVwmgkD: $config->BBCodes->addCustom('[aplay-wy id={URL?}][/aplay-wy]", "<meting-js server="netease" type="playlist" id="{URL}"></meting-js>');
 goto KBLoW0YaIY;
 KBLoW0YaIY: $config->BBCodes->addCustom('[aplay-wys id={URL?}][/aplay-wys]", "<meting-js server="netease" type="song" id="{URL}"></meting-js>');
 goto ko5n8nvI5n;
 EmhbGiLQ9G: $config->BBCodes->addCustom('[aplay-kugou_a id={URL?}][/aplay-kugou_a]", "<meting-js server="kugou" type="playlist" id="{URL}" autoplay="true"></meting-js>');
 goto uQj6upKztw;
 khjBuvQfbF: $config->MediaEmbed->add("acgtv", ["host" => "acg.tv", "extract" => "!acg\.tv/(?'mode'av|ac|sm)(?'idhao'\d+)(\?p=(?'pn'[-0-9]+))?!", "choose" => ["when" => [["test" => "@mode = 'av'", "iframe" => ["src" => "//player.bilibili.com/player.html?aid={@idhao}"]], ["test" => "@mode = 'ac'", "iframe" => ["src" => "//www.acfun.cn/player/ac{@idhao}"]], ["test" => "@mode = 'sm'", "iframe" => ["src" => "//embed.nicovideo.jp/watch/sm{@idhao}"]]], "otherwise" => ["iframe" => ["src" => "//acg.tv/{@idhao}"]]]]);
 goto JT4fsU6q2J;
 eBxDg4wEOs: $config->BBCodes->addCustom('[aplay-wys_a id={URL?}][/aplay-wys_a]", "<meting-js server="netease" type="song" id="{URL}" autoplay="true"></meting-js>');
 goto SVvv8UaCOz;
 uQj6upKztw: $config->BBCodes->addCustom('[aplay-kugous_a id={URL?}][/aplay-kugous_a]", "<meting-js server="kugou" type="song" id="{URL}" autoplay="true"></meting-js>');
 goto IwIpTFvjg4;
 ikwMXEl4jP: $config->BBCodes->addCustom('[aplay-auto_a src={URL?}][/aplay-auto_a]", "<meting-js auto="{URL}" autoplay="true"></meting-js>');
 goto Dn6LVwmgkD;
 OyxOU5pKli: $config->BBCodes->addCustom('[bplay src={URL?}][/bplay]", Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force<iframe src="https://player.m1314.cn/m3u8.php?url={URL}" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" width="100%" height="500px" frameborder="0"></iframe>');
 goto nDCIYCjLMW;
 qGDkZqodsg: $config->MediaEmbed->add("acfun", ["host" => "acfun.cn", "extract" => "!acfun\.cn/v/ac(?'acid'[-0-9]+)!", "iframe" => ["src" => "//www.acfun.cn/player/ac{@acid}"]]);
 goto Rw6U11687r;
 C36SHsQvql: $config->BBCodes->addCustom("[aplay-wy_a id={URL?}][/aplay-wy_a]", '<meting-js server="netease" type="playlist" id="{URL}" autoplay="true"></meting-js>');
 goto eBxDg4wEOs;
 SVvv8UaCOz: $config->BBCodes->addCustom("[aplay-qq_a id={URL?}][/aplay-qq_a]", '<meting-js server="tencent" type="playlist" id="{URL}" autoplay="true"></meting-js>');
 goto DAWFO0C4xF;
 ko5n8nvI5n: $config->BBCodes->addCustom('[aplay-qq id={URL?}][/aplay-qq]", "<meting-js server="tencent" type="playlist" id="{URL}"></meting-js>');
 goto C1q2EHQ8RD;
 IwIpTFvjg4: $config->BBCodes->addCustom('[donate src={URL?}][/donate]", "<iframe style="overflow-x: hidden;
 overflow-y: hidden;
 border: 0xp none #fff;
 min-height: 230px;
 width: 100%;
" src="{URL}" frameborder="0" scrolling="no"></iframe>');
 goto qGDkZqodsg;
 Rw6U11687r: $config->MediaEmbed->add("bilibili", ["host" => ["bilibili.com", "b23.tv"], "extract" => ["!bilibili\.com/video(/av(?'aid'[-0-9]+))|(/BV(?'bvid'[-0-9A-Z_a-z]+))(\?p=(?'pn'[-0-9]+))?!", "!b23\.tv/(/av(?'aid'[-0-9]+))|(/BV(?'bvid'[-0-9A-Z_a-z]+))(/p(?'pn'[-0-9]+))?!"], "iframe" => ["src" => "//player.bilibili.com/player.html?aid={@aid}&bvid={@bvid}&page={@pn}"]]);
 goto D3FhhE0mwa;
 C1q2EHQ8RD: $config->BBCodes->addCustom("[aplay-qqs id={URL?}][/aplay-qqs]", '<meting-js server="tencent" type="song" id="{URL}"></meting-js>');
 goto bqEwntU1rD;
 DAWFO0C4xF: $config->BBCodes->addCustom("[aplay-qqs_a id={URL?}][/aplay-qqs_a]", '<meting-js server="tencent" type="song" id="{URL}" autoplay="true"></meting-js>');
 goto EmhbGiLQ9G;
 bqEwntU1rD: $config->BBCodes->addCustom("[aplay-kugou id={URL?}][/aplay-kugou]", '<meting-js server="kugou" type="playlist" id="{URL}"></meting-js>');
 goto Y2EGt5yGGA;
 nDCIYCjLMW: $config->BBCodes->addCustom("[aplay-auto src={URL?}][/aplay-auto]", '<meting-js auto="{URL}"></meting-js>');
 goto ikwMXEl4jP;
 Y2EGt5yGGA: $config->BBCodes->addCustom("[aplay-kugous id={URL?}][/aplay-kugous]", '<meting-js server="kugou" type="song" id="{URL}"></meting-js>');
 goto C36SHsQvql;
 JT4fsU6q2J: })];
